### ISSUE TITLE
Transfer to sensu-plugins

### ISSUE THREAD

**Issue by lagartoflojo** [lagartoflojo/sensu-plugins-rocket-chat#1]
Hi,
I created this handler for RocketChat based on [sensu-plugins-telegram](https://github.com/sensu-plugins/sensu-plugins-telegram).
Can we transfer it to the sensu-plugins organization?

Ping @amdprophet @barryorourke @jaredledvina @majormoses @mattyjones @portertech @sstarcher  @tas50 @thomasriley

**Comment by majormoses** [comment]
Yup please open an issue here: https://github.com/sensu-plugins/community/issues/new and indicate if you would like to keep maintaining it. I will be traveling for the holidays so I am unlikely to get to it before the weekend.

**Comment by lagartoflojo** [comment]
Thank you!
